language: php
php:
    - "5.4"
    - "5.3"
    - "5.5"
    - "5.6"
    - hhvm
before_install:
    - git submodule update --init --recursive
script: phpunit --bootstrap "base/lib/tests/RapilaTestLoader.php" "./base/lib/tests/TestEverything"
