language: php
php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "7.1"
    - "nightly"
    - "hhvm"
env: RAPILA_ENVIRONMENT=test PHPUNIT_PATH=phpunit MIGRATION_SUDO=env SKIP_ICONV_TESTS=1
sudo: false
before_install:
    - git submodule update --init --recursive
    - base/scripts/create-folders.sh
    - base/scripts/generate-model.sh
script: ./base/scripts/run-tests.sh
addons:
  apt:
    packages:
    - locales
    - language-pack-de
    - language-pack-uk
    - language-pack-en
