general:
  multilingual:   true
  caching:        true
  use_full_page_cache: false    

domain_holder:
  name:   'playground'
  email:  'info@example.com'
  domain: 'example.com'

developer:
  email: cms@example.com

frontend:
  main_template: main
  protect_email_addresses: true
  doctype: xhtml5
  re_captcha_private_key: 'change-this'
  re_captcha_public_key: 'change-this'

encoding:
  db: utf-8
  browser: utf-8

admin:
  title: 'Admin: rapila — {{module_name}}'

  # set this to false if your containers overlap
  use_parsed_css_in_config: false
  
  # document and link lists can be restricted to single category selection (which is simpler to use)
  list_allows_multiple_categories: false
  
# default config for ckeditor
# important note: always requires space after comma ", " in order to function properly
text_module:  
  toolbar: 
    - 
      - ["Bold", "Italic"]
      - ["Link", "Unlink", "Anchor", "-", "Image"]
      - ["NumberedList", "BulletedList", "Blockquote"]
      - ["Undo", "Redo", "-", "Find"]
      - ["Styles", "Format"]
    -
      - ["Subscript", "Superscript", "-", "Maximize"]
      - ["HorizontalRule", "Smiley", "SpecialChar", "-", "RemoveFormat", "Scayt", "ShowBlocks"]
      - ["Source"]
  richtext_width: 700

session_default:
  language: en

#navigation configuration
meta_navigation:
  language_chooser:
    template: language
    template_active: language_active
    show_active_language: true

navigations:
  main:
    1: 
      - {template: main_current, on: 'is_current'}
      - {template: main_active, on: 'is_active'}
      - {template: main_default}
  breadcrumb:
    show_hidden: true
    all:
      - {template: bc_last, on: 'is_current'}
      - {template: bc, on: 'is_active'}
  sub:
    0:
      - {show: true}
    1:
      - {template: secondary_wrapper, on: 'is_active&has_children'}
      - {show: false}
    all: 
      - {template: secondary_level_current, on: is_current}
      - {template: secondary_level_default, on: is_child_of_current|is_sibling_of_active|is_active}
      - {show: false}
  top_css:
    no_newline: true
    0:
      - {template_inline: '{{name}}', on: is_current}
    1:
      - {template_inline: '{{name}}', on: is_active}

