# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:

name: CI

jobs:
  unit-tests:
    name: Unit tests

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php-version: ['5.3', '5.4', '5.5', '5.6']

    env:
      RAPILA_ENVIRONMENT: test
      LANG: en_US.UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl,sqlite,iconv
          coverage: none

      - name: Prepare
        run: |
          sudo apt-get -y install sqlite3 locales language-pack-de language-pack-uk language-pack-en
          composer global require phpunit/phpunit:^3
          ./base/scripts/create-folders.sh
          ./base/scripts/generate-model.sh

      - name: Run Tests
        run: ./base/scripts/run-tests.sh
